export const HISTORY_CREATE_REQUEST = "HISTORY_CREATE_REQUEST";
export const HISTORY_CREATE_SUCCESS = "HISTORY_CREATE_SUCCESS";
export const HISTORY_CREATE_RESET = "HISTORY_CREATE_RESET";

export const HISTORY_PAY_REQUEST = "HISTORY_PAY_REQUEST";
export const HISTORY_PAY_SUCCESS = "HISTORY_PAY_SUCCESS";
export const HISTORY_PAY_RESET = "HISTORY_PAY_RESET";

export const HISTORY_DELIVER_REQUEST = "HISTORY_DELIVER_REQUEST";
export const HISTORY_DELIVER_SUCCESS = "HISTORY_DELIVER_SUCCESS";

export const HISTORY_DELIVER_RESET = "HISTORY_DELIVER_RESET";

export const HISTORY_DETAILS_REQUEST = "HISTORY_DETAILS_REQUEST";
export const HISTORY_DETAILS_SUCCESS = "HISTORY_DETAILS_SUCCESS";

export const HISTORY_MINE_LIST_REQUEST = "HISTORY_MINE_LIST_REQUEST";
export const HISTORY_MINE_LIST_SUCCESS = "HISTORY_MINE_LIST_SUCCESS";

export const HISTORY_LIST_REQUEST = "HISTORY_LIST_REQUEST";
export const HISTORY_LIST_SUCCESS = "HISTORY_LIST_SUCCESS";

export const HISTORY_DELETE_REQUEST = "HISTORY_DELETE_REQUEST";
export const HISTORY_DELETE_SUCCESS = "HISTORY_DELETE_SUCCESS";
export const HISTORY_DELETE_RESET = "HISTORY_DELETE_RESET";
