export const HISTORY_DETAILS_REQUEST = "HISTORY_DETAILS_REQUEST";
export const HISTORY_DETAILS_SUCCESS = "HISTORY_DETAILS_SUCCESS";

export const HISTORY_LIST_REQUEST = "HISTORY_LIST_REQUEST";
export const HISTORY_LIST_SUCCESS = "HISTORY_LIST_SUCCESS";