export const IMAGES_UPLOAD_REQUEST = "IMAGES_UPLOAD_REQUEST";
export const IMAGES_UPLOAD_SUCCESS = "IMAGES_UPLOAD_SUCCESS";

export const IMAGES_DESTROY_REQUEST = "IMAGES_DESTROY_REQUEST";
export const IMAGES_DESTROY_SUCCESS = "IMAGES_DESTROY_SUCCESS";

export const IMAGES_RESET = "IMAGES_RESET";
